// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ69QtpKvWYNBXsHI_nVVonZxijcvUdUw',
    appId: '1:823940242544:web:33b26c5d5eba2ea9a828b5',
    messagingSenderId: '823940242544',
    projectId: 'biolens-ef25c',
    authDomain: 'biolens-ef25c.firebaseapp.com',
    storageBucket: 'biolens-ef25c.appspot.com',
    measurementId: 'G-XWRFRY37LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0G7NwXmDOWOiypVQufiNUu1N7kdb9oTk',
    appId: '1:823940242544:android:c8b99740fe1c082da828b5',
    messagingSenderId: '823940242544',
    projectId: 'biolens-ef25c',
    storageBucket: 'biolens-ef25c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYeq-tu8XG04eUp0niHhIcEUfGwF_KTfw',
    appId: '1:823940242544:ios:4af335ae13b03857a828b5',
    messagingSenderId: '823940242544',
    projectId: 'biolens-ef25c',
    storageBucket: 'biolens-ef25c.appspot.com',
    iosClientId: '823940242544-kmnpl1k1ds8cdqs08h2bh7skr4677j0k.apps.googleusercontent.com',
    iosBundleId: 'com.polymathe.biolensback',
  );
}
